### ISSUE TITLE
Have command take an argument

### ISSUE THREAD

**Issue by anthonyjclark** [AWtnb/vscode-cursor-eraser#2]
I'd like to use this extension to remove cursors from empty lines. I am using a modal editing extension (https://github.com/DCsunset/vscode-modal-editor), and I'd like to add a key binding to remove cursors from lines that are empty. Here is what I'd like it to look like:

```js
"0": { command: "cursor-eraser.erase-match", args: "^$" },
```

However, the [registered command](https://github.com/AWtnb/vscode-cursor-eraser/blob/551e9b29ef511463967a9b239af4d7657b85afd3/src/extension.ts#L82C48-L82C73) does not take an argument so I cannot pass an argument in this manner. [`replayRecord`](https://github.com/DCsunset/vscode-modal-editor/blob/13420163af78a927f2aa84357fae571e96be6893/src/commands.ts#L626) is an example of a registered command that does take an argument.

I looked into the internals a bit, and it looks like it might be reasonable to do a refactor so that the command takes an argument. If the argument is `null` then it could fallback on `showInputBox`.

Is this something you'd be willing to implement? If not, I might find time to give it a try sometime in the future.

**Comment by AWtnb** [comment]
Issue Thank you. That's a good idea!
I didn't know that `registerTextEditorCommand` takes arguments.

I see that [DCsunset/vscode-modal-editor](https://github.com/DCsunset/vscode-modal-editor) is an extension that allows you to assign key bindings to arbitrary commands (sorry if I'm not understanding the feature correctly).

I will try to implement it.

**Comment by AWtnb** [comment]
v0.2.0 is released. `cursor-eraser.keep-match` and `cursor-eraser.erase-match` now accept arguments.

I do not use [DCsunset/vscode-modal-editor](https://github.com/DCsunset/vscode-modal-editor), so I have not tested with that extension.
However, as I added in the readme, I have verified it by specifying `args` for the command in `keybindings.json`.

Is this implementation as noted in this issue?

**Comment by anthonyjclark** [comment]
Wow, that was fast! Thank you for considering the issue. It works great!


https://github.com/AWtnb/vscode-cursor-eraser/assets/4173647/f8ca75e2-5a00-4ebd-9545-355befcac9bf
